colors = ("red", "blue", "green", "yellow", "blue")
print("First color:", colors[0])    
print("Last color:", colors[-1])
blue_count = colors.count("blue")
print("Number of times 'blue' appears:", blue_count)
